### ISSUE TITLE
Run in a separate thread

### ISSUE THREAD

**Issue by xnl-h4ck3r** [marduc812/BurpSuiteHistoryExplorer#2]
Hey @marduc812 , this is a great extension and can be really useful, but is it possible to run the search in a separate thread because when I run a regex search (even a basic one) it just freezes the whole of Burp until its complete (which can take a while on big projects). Running the search in a separate thread should allow the rest of Burp to be responsive while it searches. Many thanks

**Comment by marduc812** [comment]
Hello @xnl-h4ck3r. I see what you are facing. I will take a look.
Thanks for the error message also. I will try to find a solution for that.

**Comment by marduc812** [comment]
Hello @xnl-h4ck3r 
I make the extension run on a separate thread. 
I would appreciate if you gave it a try, since I don't have such a large Burp project at the moment. 
Currently when searching it disables the search button till the search is completed. It runs on 4 threads. In the future I could add an option on how many threads it should use for search. If that works I am going to push the update and inform also the Burp Suite team. Also I hope it will fix the memory issue, since I guess 8GB is too large to load into memory in a single run. 

[HistoryExplorer-1.0-SNAPSHOT.jar.zip](https://github.com/marduc812/BurpSuiteHistoryExplorer/files/14323884/HistoryExplorer-1.0-SNAPSHOT.jar.zip)

**Comment by xnl-h4ck3r** [comment]
Hi @marduc812. Thanks, that version did solve the issue of it freezing the rest of Burp. I could use the rest of Burp no problem.
However, the memory use of Burp was 650.3MB when I started the search, and in less than a few minutes it went up to 7.88GB and I had to manually kill Burp :/ I just did a basic regex test. This relates to the other issue I logged. Thanks

**Comment by marduc812** [comment]
@xnl-h4ck3r Can you tell me on what OS are you running and also if you could tell me an example of a regex?
I am using mac os and i have a project with 42k requests which is my biggest one, used a regex like `.*:.*` and I didn't face such an issue so far. I would like to try to reproduce it.

**Comment by xnl-h4ck3r** [comment]
Hi. I am using Windows 11 Pro and I am using Burp Pro v2024.1.1.1-26891 (Early Adopter) version. 
I used the regex `login[0-9]?\.target\.com` initially, but the last test I did I just put `testing`. Both times it used all memory and logged an Out Of Memory error

**Comment by marduc812** [comment]
Hello @xnl-h4ck3r.
I changed the filtering approach and I let burp do the filtering of the requests and then the extension does some extra filtering on the requests from Burp Suite. This limits heavily the amount of memory needed, except if the regex filter is so generic that it would still load all the requests/responses.
[HistoryExplorer-1.0-SNAPSHOT.jar.zip](https://github.com/marduc812/BurpSuiteHistoryExplorer/files/14330067/HistoryExplorer-1.0-SNAPSHOT.jar.zip)

Can you give it a try and tell me how it goes? On the output tab of the extension it prints how many request/response pairs were returned by Burp.

**Comment by xnl-h4ck3r** [comment]
Hi @marduc812. That worked perfectly, no more memory issues!! Many thanks

**Comment by marduc812** [comment]
Fixed at https://github.com/marduc812/BurpSuiteHistoryExplorer/commit/aa863ed90af1ac2ac04ecb6dde488de378112053
thanks for bring it up @xnl-h4ck3r
